project:
  type: website

website:
  title: "Henk Griffioen"
  navbar:
    left:
      - projects.qmd
      - posts.qmd
      - resume.qmd

format:
  html:
    theme:
      - default
      - lukoki.scss
    css: styles.css
    toc: true



